### PR TITLE
Add a background image

### PR DESCRIPTION
**Pull request by CodeGuy92**
Yes.

### CODE REVIEW

**Comment by leahcimto** [comment]
Just letting you know you can make a branch here and then make a PR.

**Review by leahcimto — CHANGES_REQUESTED** [review]
Upon reviewing this I noticed that the page looked like the following:
Screen Shot 2021-04-06 at 5 16 25 PM

**Comment by CodeGuy92** [comment]
Actually, no it won't. It will look like how it looks now, but the BG image will be some blurred leaves

**Comment by leahcimto** [comment]
What I meant by that was that is how it looks for me right now upon previewing it.

**Comment by CodeGuy92** [comment]
what did u use to review it

**Comment by CodeGuy92** [comment]
I'll just... nevermind

**Comment by leahcimto** [comment]
I opened it locally on my computer.

**Pull request closed without merging**
